# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup (Hidden tab summary)
title:            STAT400
tagline:          'Statistics and Probability I'
description:      'Instructor: Albert Yu'
url:              https://stat400.github.io/
baseurl:          /
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Alexander Li'
  url:            https://github.com/akevli

paginate:         1000
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

# Google Analytics
google_analytics: G-CEYE831DPQ

exclude:
  - .jekyll-cache
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

